// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo.proto

package echo

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoIn struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Order                int32    `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoIn) Reset()         { *m = EchoIn{} }
func (m *EchoIn) String() string { return proto.CompactTextString(m) }
func (*EchoIn) ProtoMessage()    {}
func (*EchoIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{0}
}

func (m *EchoIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoIn.Unmarshal(m, b)
}
func (m *EchoIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoIn.Marshal(b, m, deterministic)
}
func (m *EchoIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoIn.Merge(m, src)
}
func (m *EchoIn) XXX_Size() int {
	return xxx_messageInfo_EchoIn.Size(m)
}
func (m *EchoIn) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoIn.DiscardUnknown(m)
}

var xxx_messageInfo_EchoIn proto.InternalMessageInfo

func (m *EchoIn) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *EchoIn) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

type EchoOut struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Order                int32    `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoOut) Reset()         { *m = EchoOut{} }
func (m *EchoOut) String() string { return proto.CompactTextString(m) }
func (*EchoOut) ProtoMessage()    {}
func (*EchoOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{1}
}

func (m *EchoOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoOut.Unmarshal(m, b)
}
func (m *EchoOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoOut.Marshal(b, m, deterministic)
}
func (m *EchoOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoOut.Merge(m, src)
}
func (m *EchoOut) XXX_Size() int {
	return xxx_messageInfo_EchoOut.Size(m)
}
func (m *EchoOut) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoOut.DiscardUnknown(m)
}

var xxx_messageInfo_EchoOut proto.InternalMessageInfo

func (m *EchoOut) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *EchoOut) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func init() {
	proto.RegisterType((*EchoIn)(nil), "EchoIn")
	proto.RegisterType((*EchoOut)(nil), "EchoOut")
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor_08134aea513e0001) }

var fileDescriptor_08134aea513e0001 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4d, 0xce, 0xc8,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe0, 0x62, 0x73, 0x4d, 0xce, 0xc8, 0xf7, 0xcc,
	0x13, 0x12, 0xe0, 0x62, 0xce, 0x2d, 0x4e, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31,
	0x85, 0x44, 0xb8, 0x58, 0xf3, 0x8b, 0x52, 0x52, 0x8b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83,
	0x20, 0x1c, 0x25, 0x43, 0x2e, 0x76, 0x90, 0x0e, 0xff, 0xd2, 0x12, 0x62, 0xb5, 0x18, 0x29, 0x73,
	0xb1, 0x80, 0xb4, 0x08, 0x49, 0x43, 0x69, 0x76, 0x3d, 0x88, 0x9d, 0x52, 0x1c, 0x7a, 0x50, 0xa3,
	0x94, 0x18, 0x92, 0xd8, 0xc0, 0x0e, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x81, 0x99, 0x04,
	0x8b, 0x9e, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EchoClient interface {
	Echo(ctx context.Context, in *EchoIn, opts ...grpc.CallOption) (*EchoOut, error)
}

type echoClient struct {
	cc *grpc.ClientConn
}

func NewEchoClient(cc *grpc.ClientConn) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) Echo(ctx context.Context, in *EchoIn, opts ...grpc.CallOption) (*EchoOut, error) {
	out := new(EchoOut)
	err := c.cc.Invoke(ctx, "/Echo/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoServer is the server API for Echo service.
type EchoServer interface {
	Echo(context.Context, *EchoIn) (*EchoOut, error)
}

func RegisterEchoServer(s *grpc.Server, srv EchoServer) {
	s.RegisterService(&_Echo_serviceDesc, srv)
}

func _Echo_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Echo/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Echo(ctx, req.(*EchoIn))
	}
	return interceptor(ctx, in, info, handler)
}

var _Echo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Echo_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echo.proto",
}
